# Generated by Django 4.2.5 on 2023-10-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=15)),
                ('zipp', models.CharField(max_length=10)),
            ],
        ),
    ]
